DATA SEGMENT
    DATA1 DB 0CDH,0BCH,0ABH,9AH,78H,56H,34H,12H
    DATA2 DB 12H,34H,56H,78H,9AH,0ABH,0BCH,0CDH
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
BG: MOV AX, DATA
    MOV DS, AX
    LEA DI, DATA1
    MOV DX, [DI]
    MOV CX, [DI+2]
    MOV BX, [DI+4]
    MOV SI, [DI+6]
    LEA DI, DATA2
    ADD DX, [DI]
    ADC CX, [DI+2]
    ADC BX, [DI+4]
    ADC SI, [DI+6]
    MOV AL, 0
    ADC AL, 0
    MOV AH, 4CH
    INT 21H
CODE ENDS
END BG